name: CodeUW Task
description: Create a CodeUW Task
title: "[Code UW]: "
labels: ["task", "codeuw"]
body:
  - type: input
    id: contact
    attributes:
      label: Contact
      description: Who can provide additional details about the task?
      placeholder: ex. netid@uw.edu
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
      placeholder: |
        A description of the work to perform. Add enough details for someone unfamiliar with the project 
        to work on the task. For L2 and L3 tasks, breaking them up in 2-3 steps will be helpful.
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: Code Repository      
      placeholder: https://github.com/...
    validations:
      required: true
  - type: input
    id: issue
    attributes:
      label: Issue link
      placeholder: https://github.com/.../issues/#    
    validations:
      required: false
  - type: dropdown
    id: level
    attributes:
      label: Version
      description: See task levels in [README.md](README.md)
      options:
        - L1
        - L2
        - L3
    validations:
      required: true
  - type: dropdown
    id: language
    attributes:
      label: What is the primary programming language for the task
      multiple: true
      options:
        - python
        - shell
        - C/C++
        - Javascript/Typescript  
        - Other (specify in the description)
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Additional dependencies
      description: Please list any additional requirements for working on the task
      placeholder: GPU, docker, aws/azure account, specific OS, etc.        
